### ISSUE TITLE
alias_assign instead of assign_expression

### ISSUE THREAD

**Issue by FabArd** [gdamore/tree-sitter-d#18]
Hi,

I am testing syntax highlighting with tree-sitter under emacs (tree-sitter + tree-sitter-langs emacs packages).
I made a test with the following file : [dmledit.d](https://github.com/buggins/dlangui/blob/master/examples/dmledit/src/dmledit.d)
When I make the following querry : 

`(type (qualified_identifier))@r`

I noticed that `editPopupItem` is selected in line 52 :

```
46 /// DIDE source file editor
47 class DMLSourceEdit : SourceEdit {
48    this(string ID) {
49       super(ID);
50        MenuItem editPopupItem = new MenuItem(null);
51        editPopupItem.add(ACTION_EDIT_COPY, ACTION_EDIT_PASTE, ACTION_EDIT_CUT, ACTION_EDIT_UNDO, ACTION_EDIT_REDO, ACTION_EDIT_INDENT, ACTION_EDIT_UNINDENT, ACTION_EDIT_TOGGLE_LINE_COMMENT, ACTION_DEBUG_START);
52        popupMenu = editPopupItem;
53        content.syntaxSupport = new DMLSyntaxSupport("");
54        setTokenHightlightColor(TokenCategory.Comment, 0x008000); // green
55        setTokenHightlightColor(TokenCategory.Keyword, 0x0000FF); // blue
56        setTokenHightlightColor(TokenCategory.String, 0xa31515);  // brown
57        setTokenHightlightColor(TokenCategory.Integer, 0xa315C0);  //
58        setTokenHightlightColor(TokenCategory.Float, 0xa315C0);  //
59        setTokenHightlightColor(TokenCategory.Error, 0xFF0000);  // red
60        setTokenHightlightColor(TokenCategory.Op, 0x503000);
61        setTokenHightlightColor(TokenCategory.Identifier_Class, 0x000080);  // blue
62    }
63    this() {
64        this("DMLEDIT");
65    }
66 }
```

the tree-sitter tree produces for this line : 

```
                    declaration_statement:
                      alias_assign:
                        identifier:
                        type:
                          qualified_identifier:
                            identifier:
```

This line is an assign expression not an alias assigment and 'editPopupItem' is not a type (cf line 50).

on my system "gentoo linux" I have installed the following packages :
- tree-sitter 0.20.7
- tree-sitter-cli 0.20.7

but I don't know if this is necessary for emacs tree-sitter.
